// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcjtUk_O0tccmE22aPkloganfUZFPZWts',
    appId: '1:325711534533:web:98846023c54b73c61813ac',
    messagingSenderId: '325711534533',
    projectId: 'ccsl-909d7',
    authDomain: 'ccsl-909d7.firebaseapp.com',
    storageBucket: 'ccsl-909d7.firebasestorage.app',
    measurementId: 'G-D5BN2Q5MBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA2vrRhrnsPlipA9hU4QrW4OVmVXWAqhs',
    appId: '1:325711534533:android:186595b64d30206e1813ac',
    messagingSenderId: '325711534533',
    projectId: 'ccsl-909d7',
    storageBucket: 'ccsl-909d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh2V5UwuW1y5eQ2dBKmc_A2vKMQ5XeJAE',
    appId: '1:325711534533:ios:c6839f89571a5cb11813ac',
    messagingSenderId: '325711534533',
    projectId: 'ccsl-909d7',
    storageBucket: 'ccsl-909d7.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh2V5UwuW1y5eQ2dBKmc_A2vKMQ5XeJAE',
    appId: '1:325711534533:ios:c6839f89571a5cb11813ac',
    messagingSenderId: '325711534533',
    projectId: 'ccsl-909d7',
    storageBucket: 'ccsl-909d7.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcjtUk_O0tccmE22aPkloganfUZFPZWts',
    appId: '1:325711534533:web:9ae1fc2c389fa1891813ac',
    messagingSenderId: '325711534533',
    projectId: 'ccsl-909d7',
    authDomain: 'ccsl-909d7.firebaseapp.com',
    storageBucket: 'ccsl-909d7.firebasestorage.app',
    measurementId: 'G-96W2L7VFS6',
  );
}
